import { containerCpuExpression } from "./containerCpu";
import { nativeResourceExpressions } from "./nativeResources";

const selector = (names: readonly string[]) => `{__name__=~"${names.join("|")}"}`;
const native = nativeResourceExpressions();

// Keep this inventory explicit: never copy arbitrary metric labels or metric names to clients.
export const inventoryQueries: Readonly<Record<string, string>> = {
    pve: selector([
        "pve_guest_info",
        "pve_node_info",
        "pve_storage_info",
        "pve_up",
        "pve_cpu_usage_ratio",
        "pve_cpu_usage_limit",
        "pve_memory_size_bytes",
        "pve_memory_usage_bytes",
        "pve_disk_size_bytes",
        "pve_disk_usage_bytes",
        "pve_uptime_seconds",
    ]),
    node: selector([
        "up",
        "node_memory_MemTotal_bytes",
        "node_memory_MemAvailable_bytes",
        "node_memory_SwapTotal_bytes",
        "node_memory_SwapFree_bytes",
        "node_boot_time_seconds",
        "node_load1",
        "node_load5",
        "node_load15",
        "node_uname_info",
        "node_filesystem_size_bytes",
        "node_filesystem_free_bytes",
        "node_filesystem_avail_bytes",
        "node_filesystem_readonly",
        "node_filesystem_device_error",
        "node_network_up",
        "node_network_speed_bytes",
        "node_network_receive_bytes_total",
        "node_disk_read_bytes_total",
        "homeassistant_sensor_data_size_gib",
        "homeassistant_entity_available",
    ]),
    applications: selector([
        "homelab_app_expected",
        "homelab_app_present",
        "homelab_app_running",
        "homelab_app_ready",
        "homelab_app_restart_count",
        "homelab_app_start_timestamp_seconds",
        "homelab_app_healthcheck_present",
        "homelab_app_collector_success",
        "homelab_app_last_run_timestamp_seconds",
        "probe_success",
        "smartctl_device_smart_status",
        "smartctl_device_temperature",
        "smartctl_device_percentage_used",
    ]),
    services: 'node_systemd_unit_state{state="active"}',
    containers: selector([
        "homelab_container_metrics_success",
        "homelab_container_last_sample_timestamp_seconds",
        "homelab_container_memory_working_set_bytes",
        "homelab_container_memory_limit_bytes",
        "homelab_container_pids",
        "homelab_container_network_shared",
    ]),
    containerCpu: containerCpuExpression(),
    containerReceive: "irate(homelab_container_network_rx_bytes_total[1m])",
    containerTransmit: "irate(homelab_container_network_tx_bytes_total[1m])",
    containerRead: "irate(homelab_container_block_read_bytes_total[1m])",
    containerWrite: "irate(homelab_container_block_write_bytes_total[1m])",
    native: selector([
        "homelab_native_app_info",
        "homelab_native_metrics_success",
        "homelab_native_last_sample_timestamp_seconds",
        "homelab_native_memory_working_set_bytes",
        "homelab_native_memory_limit_bytes",
        "homelab_native_pids",
    ]),
    nativeCpu: native.cpu,
    nativeReceive: native.receive,
    nativeTransmit: native.transmit,
    nativeRead: native.read,
    nativeWrite: native.write,
    cpu: '100 * (1 - avg by (host) (irate(node_cpu_seconds_total{mode="idle"}[1m])))',
    cores: 'count by (host) (node_cpu_seconds_total{mode="idle"})',
    receive: "irate(node_network_receive_bytes_total[1m])",
    transmit: "irate(node_network_transmit_bytes_total[1m])",
    errors: "irate(node_network_receive_errs_total[1m]) + irate(node_network_transmit_errs_total[1m])",
    drops: "irate(node_network_receive_drop_total[1m]) + irate(node_network_transmit_drop_total[1m])",
    read: "irate(node_disk_read_bytes_total[1m])",
    write: "irate(node_disk_written_bytes_total[1m])",
    operations:
        "irate(node_disk_reads_completed_total[1m]) + irate(node_disk_writes_completed_total[1m])",
    busy: "100 * irate(node_disk_io_time_seconds_total[1m])",
};
